import type { Metadata } from "next";
import {Poppins} from 'next/font/google';
import "./globals.css";


// internal imports
import Navbar from "@/components/navbar/navabar";

const Poppins_init = Poppins({
  subsets : ['latin'],
 weight : ['300','500','700']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Poppins_init.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
